### PR TITLE
fix getRequest() return value

### PR DESCRIPTION
**Pull request by ares333**
$this->getRequest()->getQuery() has no tooltip for getQuery() in controller,so fix it.

### CODE REVIEW

**Comment by elad-yosifon** [comment]
**$this->getRequest()** always returns an instance of **Yaf_Request_Abstract**
it might also return one of the derived classes..  but it is not guaranteed.

> public Yaf_Request_Abstract Yaf_Controller_Abstract::getRequest ( void ) http://php.net/manual/en/yaf-controller-abstract.getrequest.php

**Comment by ares333** [comment]
Yes you are right and I know that.The purpose is to make IDE showing the tooltip.... 
so i should find another way to achieve it.

**Comment by elad-yosifon** [comment]
you can add an inline comment like :

```
/**
 * @var MyClass $object
 */
$object = $objects[0];
```

**Comment by ares333** [comment]
3q.This is a very good project.

**Pull request closed without merging**
